name: my_med
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^4.0.1
  curved_navigation_bar: ^1.0.1
  date_count_down: ^2.1.0
  dropdown_button2: ^1.1.1
  shared_preferences: ^2.0.9
  cached_network_image: ^3.2.1
  provider: ^6.0.2
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  image_picker: ^0.8.4+11
  dropdown_search: ^4.0.1
  flutter_launcher_icons: ^0.9.2
  mockito: ^5.1.0
  flutter_keyboard_visibility: ^5.2.0
  auto_route_generator: ^4.0.0
  percent_indicator: ^4.2.2


  flutter_localizations: 
    sdk: flutter
  localization: ^2.1.0
  build_runner: ^2.1.10
  flutter_lorem: ^2.0.0

  
flutter_icons:
  image_path: "assets/launcher_icon_blue_red.png"
  android: true

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2


  flutter_lints: ^2.0.1




flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
