name: my_med
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^3.2.2
  curved_navigation_bar: ^1.0.1
  date_count_down: ^1.0.2
  dropdown_button2: ^1.1.1
  shared_preferences: ^2.0.9
  cached_network_image: ^3.2.0
  provider: ^6.0.2
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  flutter_svg: ^1.0.3
  

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  image_picker: ^0.8.4+11

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.7
  hive_generator: ^1.1.2


  flutter_lints: ^1.0.0




flutter:

  uses-material-design: true

  assets:
    - assets/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
